### ISSUE TITLE
Resize waveguide script shows incorrect waveguide length

### ISSUE THREAD

**Issue by PsKirwin** [SiEPIC/SiEPIC-Tools#166] opened 2022-02-09 08:13 UTC
Hi there,

The resize waveguide function (Waveguides -> Resize Waveguide) currently shows an incorrect waveguide length. If the waveguide is 500 nm wide, this incorrect length is always 5 times the correct length (as returned by the Measure Waveguide Length function). From looking at the script (line linked below), it appears that the culprit is the fact that the waveguide length is calculated using the underlying path's width, rather than the waveguide's relevant PCell parameter, as is done in the Measure Waveguide Length function.

https://github.com/SiEPIC/SiEPIC-Tools/blob/2943391e6f47bdc38f4a963dd6572f76714ad418/klayout_dot_config/python/SiEPIC/scripts.py#L2731

Best,
Phil

**Comment by jaspreetj** [comment] 2022-02-09 19:34
Thanks for reporting the issue. The issue is fixed in the latest commit.

**Closed as completed by jaspreetj** 2022-02-09 19:34 UTC
Labels: bug
